<?php
$nisn=$_POST['nisn'];
$as=$_POST['as'];
$lulus=$_POST['lulus'];
$nama=$_POST['nama'];
$nik=$_POST['nik'];
$tempatlahir=$_POST['tempatlahir'];
$foto=$_POST['foto'];
$jk=$_POST['jk'];
$alamat=$_POST['alamat'];
$desa=$_POST['desa'];
$kecamatan=$_POST['kecamatan'];
$kabupaten=$_POST['kabupaten'];
$email=$_POST['email'];
$foto=$_POST['foto'];
$nokk=$_POST['nokk'];
$ayah=$_POST['ayah'];
$agama=$_POST['agama'];
$job=$_POST['job'];
$ibu=$_POST['ibu'];
$agama=$_POST['agama'];
$job=$_POST['job'];
$alortu=$_POST['alortu'];
$desa=$_POST['desa'];
$kecamatan=$_POST['kecamatan'];
$kabupaten=$_POST['kabupaten'];
$provinsi=$_POST['provinsi'];

echo "Nisn : ".$nisn."<br>";
echo "Asal Sekolah : ".$as."<br>";
echo "Tahun Lulus : ".$lulus."<br>";
echo "Nama : ".$nama."<br>";
echo "NIK : ".$nik."<br>";
echo "Tempat Lahir : ".$tempatlahir."<br>";
echo "File : ".$foto."<br>";
echo "Jenis Kelamin : ".$jk."<br>";
echo "Alamat : ".$alamat."<br>";
echo "Desa/Kel : ".$desa."<br>";
echo "Kecamatan : ".$kecamatan."<br>";
echo "Kabupaten : ".$kabupaten."<br>";
echo "Provinsi : ".$provinsi."<br>";
echo "Alamat : ".$alamat."<br>";
echo "File : ".$foto."<br>";
echo "No KK : ".$nokk."<br>";
echo "Ayah Kandung : ".$ayah."<br>";
echo "Agama : ".$agama."<br>";
echo "Pekerjaan : ".$job."<br>";
echo "Ibu Kandung : ".$ibu."<br>";
echo "Agama : ".$agama."<br>";
echo "Pekerjaan : ".$job."<br>";
echo "Aalamat Orang Tua : ".$alortu."<br>";
echo "Desa/Kel : ".$desa."<br>";
echo "Kecamatan : ".$kecamatan."<br>";
echo "Kabupaten : ".$kabupaten."<br>";
echo "Provinsi : ".$provinsi."<br>";
?>